spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminpanel
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
    
jwt:
  secret: this is simple secret it will be changed so don't take it as final
  expireInDays: 2
  tokenPrefix: Bearer 